"""Add job tracking fields for user description and message counting

Revision ID: job_tracking_fields
Revises: 0465f20dd92f
Create Date: 2025-01-25 09:59:23.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'job_tracking_fields'
down_revision: Union[str, None] = 'consolidated_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_description', sa.Text(), nullable=True))
    
    # Add nullable columns first
    op.add_column('jobs', sa.Column('messages_sent', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('messages_planned', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('completion_percentage', sa.Float(), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE jobs SET messages_sent = 0 WHERE messages_sent IS NULL")
    op.execute("UPDATE jobs SET messages_planned = 0 WHERE messages_planned IS NULL")
    op.execute("UPDATE jobs SET completion_percentage = 0.0 WHERE completion_percentage IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('jobs', 'messages_sent', nullable=False, server_default='0')
    op.alter_column('jobs', 'messages_planned', nullable=False, server_default='0')
    op.alter_column('jobs', 'completion_percentage', nullable=False, server_default='0.0')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server defaults first
    op.alter_column('jobs', 'completion_percentage', server_default=None)
    op.alter_column('jobs', 'messages_planned', server_default=None)
    op.alter_column('jobs', 'messages_sent', server_default=None)
    
    # Drop columns
    op.drop_column('jobs', 'completion_percentage')
    op.drop_column('jobs', 'messages_planned')
    op.drop_column('jobs', 'messages_sent')
    op.drop_column('jobs', 'user_description')
    # ### end Alembic commands ###
